version: '3'
services:
  app:
    image: wilfongjt/lb-a1
    build:
      context: ./
    command: >
      bash -c "npm install && npm run dev" 
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
    environment:
      - LB_ENV=
